ARC_DEPS := toolA
ARC_VERSION := 7890

.PHONY: build
build:
	@echo "Definitely building"

.PHONY: clean
clean:
	@echo "Definitely cleaning"

.PHONY: prepare-rebuild
prepare-rebuild:
	@echo "Definitely preparing rebuild"

.PHONY: get-deps
get-deps:
	@echo $(ARC_DEPS)

.PHONY: get-version
get-version:
	@echo $(ARC_VERSION)
